### ISSUE TITLE
About your usefull plugin !

### ISSUE THREAD

**Issue by flopi34** [eschmar/wp_woocommerce-isotope#1]
Hallo !
I'd like first of all thank you for creating this really usefull plugin for wordpress.
I have questions about this and i want forst to know if i can contact you ... but i didn't fint anywhere your email ...
Please send me a reply if i can contact you ...
Many thanks.
Flopi34

**Comment by eschmar** [comment]
Hey Flopi34
Sure, you can write here or send me an email to `removed`.
cheers,
marcel

**Comment by flopi34** [comment]
Hi !
I installed your plugin on my site (it works well on my woo commerce main shop page !) but i would like to use it on other pages where i have displayed products with the woocommerce shortcodes.

I explain : I sell cats and dogs biscuits (dry food for pets).
So i have set categories and many subcategories for the products : 

> Dogs (main category)
>      > Small-size Dogs (sub-category) like Chiwawa ...
>           > Young small-size dogs (sub-sub-category)
>           > Adult small-size dogs (sub-sub-category)
>           > Old small-size dogs (sub-sub-category)
>      > Medium-size Dogs (sub-category) like bulldog ...
>           > Young medium-size dogs (sub-sub-category)
>           > Adult medium-size dogs (sub-sub-category)
>           > Old medium-size dogs (sub-sub-category)
>      > Big-size Dogs (sub-category) like golden retriever ...
>           > Young big-size dogs (sub-sub-category)
>           > Adult big-size dogs (sub-sub-category)
>           > Old big-size dogs (sub-sub-category)
> Cats (main category)
>      > and the same hierarchical tree as for dogs ...

I created some pages to display products belonging to one particular main category or sub or sub-sub-category, using the "woocommerce shortcode product categories by slug".
I would like to be able to filter products on theses particular pages using your shortcode, but it seem to work as these pages are not "archive pages". (there is no category menu displaying above the products grid).

Do i have done something wrong ? Does your plugin works with the woocommerce shortcodes ?

Many thanks for your answer !

Flopi34

**Comment by eschmar** [comment]
Hi Flopi34

Glad to hear that you like the plugin :)

I just looked briefly in the source code of woocommerce. As far as i can tell, the shortcode you're using renders the correct template, however the action `woocommerce_before_shop_loop` is never executed. This means you would have to track down the correct action and hook the function `woocommerce_isotope_render_list` on to it. As a starting point you can find the shortcode you're looking for in [includes/class-wc-shortcodes.php](https://github.com/woothemes/woocommerce/blob/00fc089abe6ff112475beed1c57b1d7aaacec5d8/includes/class-wc-shortcodes.php).

I currently don't have time to look into that any further. If you can't get it to work you can tell me and i'll probably be able to give it a shot this weekend.

Cheers,
Marcel
